/**
 * DOMAINE — codes propriétaires du SATCAT (catalogue satellite de Celestrak).
 *
 * Le champ `OWNER` du SATCAT est un code de 2 à 5 lettres désignant l'État ou
 * l'organisation responsable de l'objet — ce n'est pas exactement une
 * nationalité : `ESA` est une agence intergouvernementale, `ITSO` et `SES` sont
 * des opérateurs privés, `CIS` désigne les objets soviétiques puis russes.
 *
 * Liste des codes utilisés par Celestrak (source : satcat-format et boxscore).
 */

export interface OwnerInfo {
  /** Libellé FR affiché. */
  readonly label: string;
  /** Drapeau (émoji) quand un pays unique est identifiable, sinon ''. */
  readonly flag: string;
  /** Nature de l'entité : État, agence spatiale, organisation, opérateur privé. */
  readonly kind: 'état' | 'agence' | 'organisation' | 'opérateur';
}

export const OWNERS: Record<string, OwnerInfo> = {
  US: { label: 'États-Unis', flag: '🇺🇸', kind: 'état' },
  CIS: { label: 'Russie / ex-URSS', flag: '🇷🇺', kind: 'état' },
  PRC: { label: 'Chine', flag: '🇨🇳', kind: 'état' },
  JPN: { label: 'Japon', flag: '🇯🇵', kind: 'état' },
  IND: { label: 'Inde', flag: '🇮🇳', kind: 'état' },
  FR: { label: 'France', flag: '🇫🇷', kind: 'état' },
  UK: { label: 'Royaume-Uni', flag: '🇬🇧', kind: 'état' },
  GER: { label: 'Allemagne', flag: '🇩🇪', kind: 'état' },
  IT: { label: 'Italie', flag: '🇮🇹', kind: 'état' },
  CA: { label: 'Canada', flag: '🇨🇦', kind: 'état' },
  SPN: { label: 'Espagne', flag: '🇪🇸', kind: 'état' },
  SES: { label: 'SES (Luxembourg)', flag: '🇱🇺', kind: 'opérateur' },
  LUXE: { label: 'Luxembourg', flag: '🇱🇺', kind: 'état' },
  NETH: { label: 'Pays-Bas', flag: '🇳🇱', kind: 'état' },
  SWED: { label: 'Suède', flag: '🇸🇪', kind: 'état' },
  NOR: { label: 'Norvège', flag: '🇳🇴', kind: 'état' },
  DEN: { label: 'Danemark', flag: '🇩🇰', kind: 'état' },
  FIN: { label: 'Finlande', flag: '🇫🇮', kind: 'état' },
  SWTZ: { label: 'Suisse', flag: '🇨🇭', kind: 'état' },
  AUS: { label: 'Australie', flag: '🇦🇺', kind: 'état' },
  AUST: { label: 'Autriche', flag: '🇦🇹', kind: 'état' },
  BEL: { label: 'Belgique', flag: '🇧🇪', kind: 'état' },
  BRAZ: { label: 'Brésil', flag: '🇧🇷', kind: 'état' },
  ARGN: { label: 'Argentine', flag: '🇦🇷', kind: 'état' },
  CHLE: { label: 'Chili', flag: '🇨🇱', kind: 'état' },
  MEX: { label: 'Mexique', flag: '🇲🇽', kind: 'état' },
  KOR: { label: 'Corée du Sud', flag: '🇰🇷', kind: 'état' },
  NKOR: { label: 'Corée du Nord', flag: '🇰🇵', kind: 'état' },
  TWN: { label: 'Taïwan', flag: '🇹🇼', kind: 'état' },
  THAI: { label: 'Thaïlande', flag: '🇹🇭', kind: 'état' },
  INDO: { label: 'Indonésie', flag: '🇮🇩', kind: 'état' },
  MALA: { label: 'Malaisie', flag: '🇲🇾', kind: 'état' },
  SING: { label: 'Singapour', flag: '🇸🇬', kind: 'état' },
  VTNM: { label: 'Viêt Nam', flag: '🇻🇳', kind: 'état' },
  PHLP: { label: 'Philippines', flag: '🇵🇭', kind: 'état' },
  PAKI: { label: 'Pakistan', flag: '🇵🇰', kind: 'état' },
  BGD: { label: 'Bangladesh', flag: '🇧🇩', kind: 'état' },
  IRAN: { label: 'Iran', flag: '🇮🇷', kind: 'état' },
  ISRA: { label: 'Israël', flag: '🇮🇱', kind: 'état' },
  TURK: { label: 'Turquie', flag: '🇹🇷', kind: 'état' },
  SAUD: { label: 'Arabie saoudite', flag: '🇸🇦', kind: 'état' },
  UAE: { label: 'Émirats arabes unis', flag: '🇦🇪', kind: 'état' },
  QAT: { label: 'Qatar', flag: '🇶🇦', kind: 'état' },
  EGYP: { label: 'Égypte', flag: '🇪🇬', kind: 'état' },
  ALG: { label: 'Algérie', flag: '🇩🇿', kind: 'état' },
  MOR: { label: 'Maroc', flag: '🇲🇦', kind: 'état' },
  NIG: { label: 'Nigeria', flag: '🇳🇬', kind: 'état' },
  RSA: { label: 'Afrique du Sud', flag: '🇿🇦', kind: 'état' },
  POL: { label: 'Pologne', flag: '🇵🇱', kind: 'état' },
  CZCH: { label: 'Tchéquie', flag: '🇨🇿', kind: 'état' },
  HUN: { label: 'Hongrie', flag: '🇭🇺', kind: 'état' },
  ROM: { label: 'Roumanie', flag: '🇷🇴', kind: 'état' },
  BUL: { label: 'Bulgarie', flag: '🇧🇬', kind: 'état' },
  GREC: { label: 'Grèce', flag: '🇬🇷', kind: 'état' },
  POR: { label: 'Portugal', flag: '🇵🇹', kind: 'état' },
  IRAQ: { label: 'Irak', flag: '🇮🇶', kind: 'état' },
  KAZ: { label: 'Kazakhstan', flag: '🇰🇿', kind: 'état' },
  UKR: { label: 'Ukraine', flag: '🇺🇦', kind: 'état' },
  BELA: { label: 'Bélarus', flag: '🇧🇾', kind: 'état' },
  EST: { label: 'Estonie', flag: '🇪🇪', kind: 'état' },
  LTU: { label: 'Lituanie', flag: '🇱🇹', kind: 'état' },
  LVA: { label: 'Lettonie', flag: '🇱🇻', kind: 'état' },
  SVN: { label: 'Slovénie', flag: '🇸🇮', kind: 'état' },
  SKOR: { label: 'Corée du Sud', flag: '🇰🇷', kind: 'état' },
  NZ: { label: 'Nouvelle-Zélande', flag: '🇳🇿', kind: 'état' },
  PERU: { label: 'Pérou', flag: '🇵🇪', kind: 'état' },
  COL: { label: 'Colombie', flag: '🇨🇴', kind: 'état' },
  ECU: { label: 'Équateur', flag: '🇪🇨', kind: 'état' },
  URY: { label: 'Uruguay', flag: '🇺🇾', kind: 'état' },
  VENZ: { label: 'Venezuela', flag: '🇻🇪', kind: 'état' },
  CRI: { label: 'Costa Rica', flag: '🇨🇷', kind: 'état' },
  GUAT: { label: 'Guatemala', flag: '🇬🇹', kind: 'état' },
  KWT: { label: 'Koweït', flag: '🇰🇼', kind: 'état' },
  AZER: { label: 'Azerbaïdjan', flag: '🇦🇿', kind: 'état' },
  BHUT: { label: 'Bhoutan', flag: '🇧🇹', kind: 'état' },
  NPL: { label: 'Népal', flag: '🇳🇵', kind: 'état' },
  LKA: { label: 'Sri Lanka', flag: '🇱🇰', kind: 'état' },
  MNG: { label: 'Mongolie', flag: '🇲🇳', kind: 'état' },
  MMR: { label: 'Birmanie', flag: '🇲🇲', kind: 'état' },
  LAOS: { label: 'Laos', flag: '🇱🇦', kind: 'état' },
  TUN: { label: 'Tunisie', flag: '🇹🇳', kind: 'état' },
  KEN: { label: 'Kenya', flag: '🇰🇪', kind: 'état' },
  ETH: { label: 'Éthiopie', flag: '🇪🇹', kind: 'état' },
  GHA: { label: 'Ghana', flag: '🇬🇭', kind: 'état' },
  ANG: { label: 'Angola', flag: '🇦🇴', kind: 'état' },
  SDN: { label: 'Soudan', flag: '🇸🇩', kind: 'état' },
  ZWE: { label: 'Zimbabwe', flag: '🇿🇼', kind: 'état' },
  RWA: { label: 'Rwanda', flag: '🇷🇼', kind: 'état' },
  MUS: { label: 'Maurice', flag: '🇲🇺', kind: 'état' },
  BOL: { label: 'Bolivie', flag: '🇧🇴', kind: 'état' },
  PRY: { label: 'Paraguay', flag: '🇵🇾', kind: 'état' },
  SVK: { label: 'Slovaquie', flag: '🇸🇰', kind: 'état' },
  IRL: { label: 'Irlande', flag: '🇮🇪', kind: 'état' },
  MCO: { label: 'Monaco', flag: '🇲🇨', kind: 'état' },
  CYP: { label: 'Chypre', flag: '🇨🇾', kind: 'état' },
  MDA: { label: 'Moldavie', flag: '🇲🇩', kind: 'état' },
  GEO: { label: 'Géorgie', flag: '🇬🇪', kind: 'état' },
  ARM: { label: 'Arménie', flag: '🇦🇲', kind: 'état' },
  UZB: { label: 'Ouzbékistan', flag: '🇺🇿', kind: 'état' },
  TKM: { label: 'Turkménistan', flag: '🇹🇲', kind: 'état' },
  BRN: { label: 'Brunei', flag: '🇧🇳', kind: 'état' },
  JOR: { label: 'Jordanie', flag: '🇯🇴', kind: 'état' },
  LBN: { label: 'Liban', flag: '🇱🇧', kind: 'état' },
  BHR: { label: 'Bahreïn', flag: '🇧🇭', kind: 'état' },
  OMAN: { label: 'Oman', flag: '🇴🇲', kind: 'état' },
  SEN: { label: 'Sénégal', flag: '🇸🇳', kind: 'état' },
  CHBZ: { label: 'Chine / Brésil (CBERS)', flag: '', kind: 'organisation' },
  FRIT: { label: 'France / Italie', flag: '', kind: 'organisation' },
  ITSO: { label: 'Intelsat', flag: '', kind: 'opérateur' },
  IM: { label: 'Inmarsat', flag: '', kind: 'opérateur' },
  EUTE: { label: 'Eutelsat', flag: '', kind: 'opérateur' },
  ESA: { label: 'Agence spatiale européenne (ESA)', flag: '🇪🇺', kind: 'agence' },
  ESRO: { label: 'ESRO (ancêtre de l’ESA)', flag: '🇪🇺', kind: 'agence' },
  EUME: { label: 'EUMETSAT', flag: '🇪🇺', kind: 'organisation' },
  EU: { label: 'Union européenne', flag: '🇪🇺', kind: 'organisation' },
  // Attention : dans le SATCAT, ASRA désigne l'agence spatiale autrichienne,
  // pas Arabsat (qui est codé AB). Vérifié sur les objets autrichiens du registre.
  ASRA: { label: 'Autriche', flag: '🇦🇹', kind: 'agence' },
  AB: { label: 'Arabsat', flag: '', kind: 'opérateur' },
  ABS: { label: 'ABS (Asia Broadcast Satellite)', flag: '', kind: 'opérateur' },
  /** Station spatiale internationale : objets rattachés au programme, multinational. */
  ISS: { label: 'Station spatiale internationale', flag: '', kind: 'organisation' },
  IRID: { label: 'Iridium', flag: '', kind: 'opérateur' },
  ROC: { label: 'Taïwan', flag: '🇹🇼', kind: 'état' },
  SAFR: { label: 'Afrique du Sud', flag: '🇿🇦', kind: 'état' },
  SGP: { label: 'Singapour', flag: '🇸🇬', kind: 'état' },
  MA: { label: 'Maroc', flag: '🇲🇦', kind: 'état' },
  FGER: { label: 'France / Allemagne', flag: '', kind: 'organisation' },
  TMMC: { label: 'Turkménistan / Monaco', flag: '', kind: 'organisation' },
  BERM: { label: 'Bermudes', flag: '🇧🇲', kind: 'état' },
  AGO: { label: 'Angola', flag: '🇦🇴', kind: 'état' },
  DJI: { label: 'Djibouti', flag: '🇩🇯', kind: 'état' },
  RASC: { label: 'RascomStar-QAF', flag: '', kind: 'opérateur' },
  NATO: { label: 'OTAN', flag: '', kind: 'organisation' },
  NICO: { label: 'New ICO', flag: '', kind: 'opérateur' },
  O3B: { label: 'O3b Networks', flag: '', kind: 'opérateur' },
  GLOB: { label: 'Globalstar', flag: '', kind: 'opérateur' },
  ORB: { label: 'ORBCOMM', flag: '', kind: 'opérateur' },
  SEAL: { label: 'Sea Launch', flag: '', kind: 'opérateur' },
  STCT: { label: 'Singapour / Taïwan', flag: '', kind: 'organisation' },
  USBZ: { label: 'États-Unis / Brésil', flag: '', kind: 'organisation' },
  RP: { label: 'Philippines', flag: '🇵🇭', kind: 'état' },
  TBD: { label: 'Propriétaire non déterminé', flag: '', kind: 'organisation' },
  UNK: { label: 'Propriétaire inconnu', flag: '', kind: 'organisation' },
};

/** Info d'un code propriétaire, avec repli lisible sur le code brut. */
export function ownerInfo(code: string | undefined): OwnerInfo & { code: string } {
  const key = (code ?? '').trim().toUpperCase();
  const known = OWNERS[key];
  if (known) return { ...known, code: key };
  return {
    code: key || 'UNK',
    label: key || 'Propriétaire inconnu',
    flag: '',
    kind: 'organisation',
  };
}
